### ISSUE TITLE
IDE freezes

### ISSUE THREAD

**Issue by patdlanger** [metalbear-co/mirrord-intellij#93]
### Bug Description

Almost always when I try to run my application with mirrord my IDE just freezes until I kill it.

I use the default settings + define the target deployment and namespace.

thread dump is attached
[mirrord_freeze.zip](https://github.com/metalbear-co/mirrord-intellij/files/12408536/mirrord_freeze.zip)

### Steps to Reproduce

1. Enable mirrord
2. Run application (in my case a Java Spring Boot app)
3.  The last log message then reads `INFO - mirrord - running mirrord with following command line: /usr/local/bin/mirrord ext -f /some/path/mirrord.json`

### Your operating system and version

Ubuntu 22.04.2 LTS, Intellij Idea Ultimate 2023.2, mirrord plugin 3.52.0

### Local process

/snap/bin/intellij-idea-ultimate

**Comment by aviramha** [comment]
Can you share your `mirrord.json` file please?

**Comment by Razz4780** [comment]
I see the plugin uses a local installation of mirrord binary under `/usr/local/bin/mirrord`. Could you provide the output of `/usr/local/bin/mirrord --version`?
Also, what build system do you use for your application? I could not reproduce with Gradle.

**Comment by patdlanger** [comment]
```json
{
    "target": {
        "path": {
            "deployment": "integration-request-batch-business-service"
        },
        "namespace": "mip"
    },
    "accept_invalid_certificates": false,
    "feature": {
        "network": {
            "incoming": {
                "mode": "mirror"
            },
            "outgoing": true
        },
        "fs": "read"
        }
}
```

```
/usr/local/bin/mirrord --version
mirrord 3.60.0
```
I previously only had the intellij plugin installed, but it started giving me warnings that new mirrord versions are available so I also installed the cli(and even before that it froze occasionally)

I use gradle 7.6 with jdk 17(semeru). I have multiple jdks installed via asdf but only use this specific jdk currently

**Comment by aviramha** [comment]
The mirrord warnings are because of #94 - next version should be sorted out!

**Comment by patdlanger** [comment]
I started intellij via terminal and got some more log messages for you that I got after I ctrl+c'd
```
^C2023-08-23 09:04:45,790 [ 154248] SEVERE - mirrord - mirrord stderr: 
java.lang.Throwable: mirrord stderr: 
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at com.metalbear.mirrord.MirrordApi.exec(MirrordApi.kt:277)
	at com.metalbear.mirrord.MirrordExecManager.start(MirrordExecManager.kt:211)
	at com.metalbear.mirrord.MirrordExecManager.start(MirrordExecManager.kt:130)
	at com.metalbear.mirrord.products.idea.IdeaRunConfigurationExtension.patchEnv(IdeaRunConfigurationExtension.kt:56)
	at com.metalbear.mirrord.products.idea.IdeaRunConfigurationExtension.updateJavaParameters(IdeaRunConfigurationExtension.kt:87)
	at com.intellij.execution.JavaRunConfigurationExtensionManager.updateJavaParameters(JavaRunConfigurationExtensionManager.kt:42)
	at com.intellij.execution.application.BaseJavaApplicationCommandLineState.lambda$setupJavaParameters$0(BaseJavaApplicationCommandLineState.java:37)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:64)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:923)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:76)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:63)
	at com.intellij.execution.application.BaseJavaApplicationCommandLineState.setupJavaParameters(BaseJavaApplicationCommandLineState.java:36)
	at com.intellij.execution.application.ApplicationCommandLineState.createJavaParameters(ApplicationCommandLineState.java:62)
	at com.intellij.spring.boot.run.SpringBootCommandLineState.createJavaParameters(SpringBootCommandLineState.java:46)
	at com.intellij.execution.configurations.JavaCommandLineState.getJavaParameters(JavaCommandLineState.java:41)
	at com.intellij.debugger.impl.GenericDebuggerRunner.lambda$doExecuteAsync$3(GenericDebuggerRunner.java:95)
	at com.intellij.execution.runners.ExecutionUtil.computeWithDataContext(ExecutionUtil.java:326)
	at com.intellij.execution.target.TargetEnvironmentAwareRunProfileState$1.run(TargetEnvironmentAwareRunProfileState.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:428)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:115)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:478)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:251)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:251)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:465)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-08-23 09:04:45,795 [ 154253] SEVERE - mirrord - IntelliJ IDEA 2023.2  Build #IU-232.8660.185
2023-08-23 09:04:45,795 [ 154253] SEVERE - mirrord - JDK: 17.0.7; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-08-23 09:04:45,796 [ 154254] SEVERE - mirrord - OS: Linux
2023-08-23 09:04:45,796 [ 154254] SEVERE - mirrord - Plugin to blame: mirrord version: 3.52.0
2023-08-23 09:04:45,799 [ 154257] SEVERE - #c.i.d.i.GenericDebuggerRunner - Failed to execute debug configuration async
java.lang.Error: mirrord failed to start
	at com.metalbear.mirrord.MirrordApi.exec(MirrordApi.kt:278)
	at com.metalbear.mirrord.MirrordExecManager.start(MirrordExecManager.kt:211)
	at com.metalbear.mirrord.MirrordExecManager.start(MirrordExecManager.kt:130)
	at com.metalbear.mirrord.products.idea.IdeaRunConfigurationExtension.patchEnv(IdeaRunConfigurationExtension.kt:56)
	at com.metalbear.mirrord.products.idea.IdeaRunConfigurationExtension.updateJavaParameters(IdeaRunConfigurationExtension.kt:87)
	at com.intellij.execution.JavaRunConfigurationExtensionManager.updateJavaParameters(JavaRunConfigurationExtensionManager.kt:42)
	at com.intellij.execution.application.BaseJavaApplicationCommandLineState.lambda$setupJavaParameters$0(BaseJavaApplicationCommandLineState.java:37)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:64)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:923)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:76)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:63)
	at com.intellij.execution.application.BaseJavaApplicationCommandLineState.setupJavaParameters(BaseJavaApplicationCommandLineState.java:36)
	at com.intellij.execution.application.ApplicationCommandLineState.createJavaParameters(ApplicationCommandLineState.java:62)
	at com.intellij.spring.boot.run.SpringBootCommandLineState.createJavaParameters(SpringBootCommandLineState.java:46)
	at com.intellij.execution.configurations.JavaCommandLineState.getJavaParameters(JavaCommandLineState.java:41)
	at com.intellij.debugger.impl.GenericDebuggerRunner.lambda$doExecuteAsync$3(GenericDebuggerRunner.java:95)
	at com.intellij.execution.runners.ExecutionUtil.computeWithDataContext(ExecutionUtil.java:326)
	at com.intellij.execution.target.TargetEnvironmentAwareRunProfileState$1.run(TargetEnvironmentAwareRunProfileState.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:428)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:115)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:478)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:251)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:251)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:465)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-08-23 09:04:45,799 [ 154257] SEVERE - #c.i.d.i.GenericDebuggerRunner - IntelliJ IDEA 2023.2  Build #IU-232.8660.185
2023-08-23 09:04:45,799 [ 154257] SEVERE - #c.i.d.i.GenericDebuggerRunner - JDK: 17.0.7; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-08-23 09:04:45,799 [ 154257] SEVERE - #c.i.d.i.GenericDebuggerRunner - OS: Linux
2023-08-23 09:04:45,799 [ 154257] SEVERE - #c.i.d.i.GenericDebuggerRunner - Plugin to blame: mirrord version: 3.52.0
2023-08-23 09:04:45,801 [ 154259]   WARN - #c.i.o.v.i.l.NativeFileWatcherImpl - Watcher terminated with exit code 130
2023-08-23 09:04:45,807 [ 154265]   WARN - #c.i.d.PerformanceWatcherImpl - UI was frozen for 79778ms, details saved to /home/patrick/.cache/JetBrains/IntelliJIdea2023.2/log/threadDumps-freeze-20230823-090331-IU-232.8660.185-Unsafe.park-79sec
2023-08-23 09:04:45,920 [ 154378] SEVERE - #c.i.u.c.Invoker - VFS is already disposed
com.intellij.serviceContainer.AlreadyDisposedException: VFS is already disposed
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.alreadyDisposed(FSRecords.java:514)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.implOrFail(FSRecords.java:106)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.getPersistentModCount(FSRecords.java:145)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.getFilesystemModificationCount(PersistentFSImpl.java:382)
	at com.intellij.openapi.vfs.PlatformVirtualFileManager.getModificationCount(PlatformVirtualFileManager.java:44)
	at com.intellij.workspaceModel.ide.impl.VirtualFileUrlBridge.findVirtualFile(VirtualFileUrlBridge.kt:37)
	at com.intellij.workspaceModel.ide.impl.VirtualFileUrlBridge.getFile(VirtualFileUrlBridge.kt:18)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.roots.ContentEntryBridge.getFile(ContentEntryBridge.kt:30)
	at com.intellij.openapi.roots.impl.RootModelBase.getContentRoots(RootModelBase.java:24)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.roots.ModuleRootComponentBridge.getContentRoots(ModuleRootComponentBridge.kt:157)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.getContentRoots(ProjectRootManagerImpl.java:221)
	at com.intellij.ide.projectView.impl.nodes.ProjectViewDirectoryHelper.getTopLevelRoots(ProjectViewDirectoryHelper.java:234)
	at com.intellij.ide.projectView.impl.nodes.ProjectViewProjectNode.getChildren(ProjectViewProjectNode.java:41)
	at com.intellij.ide.util.treeView.AbstractTreeStructureBase.getChildElements(AbstractTreeStructureBase.java:38)
	at com.intellij.ui.tree.StructureTreeModel.getValidChildren(StructureTreeModel.java:411)
	at com.intellij.ui.tree.StructureTreeModel.validateChildren(StructureTreeModel.java:329)
	at com.intellij.ui.tree.StructureTreeModel.getNode(StructureTreeModel.java:323)
	at com.intellij.ui.tree.StructureTreeModel.getChildren(StructureTreeModel.java:343)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.getNode(AsyncTreeModel.java:568)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:464)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:430)
	at com.intellij.util.concurrency.Invoker$Task.run(Invoker.java:306)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:76)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:133)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:114)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:111)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:76)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:188)
	at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:165)
	at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:433)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:24)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:249)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:227)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:215)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.lang.Exception: VFS dispose stacktrace
		at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.dispose(FSRecords.java:98)
		at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.disconnect(PersistentFSImpl.java:160)
		at com.intellij.openapi.util.ShutDownTracker.run(ShutDownTracker.java:42)
		at com.intellij.openapi.util.ShutDownTracker.lambda$new$0(ShutDownTracker.java:19)
		... 1 more
2023-08-23 09:04:45,920 [ 154378] SEVERE - #c.i.o.u.ObjectTree - VFS is already disposed
com.intellij.serviceContainer.AlreadyDisposedException: VFS is already disposed
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.alreadyDisposed(FSRecords.java:514)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.implOrFail(FSRecords.java:106)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.getNameByNameId(FSRecords.java:316)
	at com.intellij.openapi.vfs.newvfs.persistent.FileNameCache.getVFileName(FileNameCache.java:148)
	at com.intellij.openapi.vfs.newvfs.persistent.FileNameCache.getVFileName(FileNameCache.java:157)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.getNameSequence(VirtualFileSystemEntry.java:159)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.computePath(VirtualFileSystemEntry.java:265)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.getPath(VirtualFileSystemEntry.java:300)
	at com.intellij.openapi.vfs.VirtualFile.getPresentableUrl(VirtualFile.java:195)
	at com.intellij.vcs.log.util.VcsLogUtil.lambda$getProvidersMapText$5(VcsLogUtil.java:327)
	at com.intellij.openapi.util.text.Strings.join(Strings.java:658)
	at com.intellij.openapi.util.text.Strings.join(Strings.java:648)
	at com.intellij.openapi.util.text.Strings.join(Strings.java:628)
	at com.intellij.openapi.util.text.StringUtil.join(StringUtil.java:1478)
	at com.intellij.vcs.log.util.VcsLogUtil.getProvidersMapText(VcsLogUtil.java:327)
	at com.intellij.vcs.log.impl.VcsLogManager.dispose(VcsLogManager.java:262)
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:129)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:161)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:262)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:250)
	at com.intellij.vcs.log.impl.VcsProjectLog.disposeLogInternal(VcsProjectLog.kt:160)
	at com.intellij.vcs.log.impl.VcsProjectLog.access$disposeLogInternal(VcsProjectLog.kt:53)
	at com.intellij.vcs.log.impl.VcsProjectLog$disposeLogInternal$1.invokeSuspend(VcsProjectLog.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.intellij.vcs.log.impl.VcsProjectLog$shutdownTask$1.run(VcsProjectLog.kt:91)
	at com.intellij.openapi.util.ShutDownTracker.run(ShutDownTracker.java:42)
	at com.intellij.openapi.util.ShutDownTracker.lambda$new$0(ShutDownTracker.java:19)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.lang.Exception: VFS dispose stacktrace
		at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.dispose(FSRecords.java:98)
		at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.disconnect(PersistentFSImpl.java:160)
		... 3 more
2023-08-23 09:04:45,921 [ 154379] SEVERE - #c.i.u.c.Invoker - IntelliJ IDEA 2023.2  Build #IU-232.8660.185
2023-08-23 09:04:45,921 [ 154379] SEVERE - #c.i.o.u.ObjectTree - IntelliJ IDEA 2023.2  Build #IU-232.8660.185
2023-08-23 09:04:45,921 [ 154379] SEVERE - #c.i.u.c.Invoker - JDK: 17.0.7; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-08-23 09:04:45,921 [ 154379] SEVERE - #c.i.o.u.ObjectTree - JDK: 17.0.7; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-08-23 09:04:45,921 [ 154379] SEVERE - #c.i.u.c.Invoker - OS: Linux
2023-08-23 09:04:45,921 [ 154379] SEVERE - #c.i.o.u.ObjectTree - OS: Linux
```

**Comment by aviramha** [comment]
Did you try running from the cli? did it work?

**Comment by patdlanger** [comment]
> Did you try running from the cli? did it work?

yes, it runs fine using the cli

**Comment by Razz4780** [comment]
This is quite strange. Could you provide the output of `/usr/local/bin/mirrord ext -f /your/path/to/mirrord.json` and how long it takes to complete?

**Comment by patdlanger** [comment]
> This is quite strange. Could you provide the output of `/usr/local/bin/mirrord ext -f /your/path/to/mirrord.json` and how long it takes to complete?

```
time /usr/local/bin/mirrord ext -f /xyz/mirrord.json
{"type":"NewTask","name":"mirrord preparing to launch","parent":null}
{"type":"NewTask","name":"extracting layer","parent":"mirrord preparing to launch"}
{"type":"FinishedTask","name":"extracting layer","success":true,"message":"layer extracted"}
{"type":"NewTask","name":"checking operator","parent":"mirrord preparing to launch"}
{"type":"FinishedTask","name":"checking operator","success":false,"message":"unable to check if operator exists, probably due to RBAC"}
{"type":"NewTask","name":"detecting OpenShift...","parent":"mirrord preparing to launch"}
{"type":"FinishedTask","name":"detecting OpenShift...","success":true,"message":"OpenShift was not detected."}
{"type":"NewTask","name":"checking if node is allocatable...","parent":"mirrord preparing to launch"}
{"type":"Warning","message":"unable to check if node is allocatable"}
{"type":"FinishedTask","name":"checking if node is allocatable...","success":false,"message":null}
{"type":"NewTask","name":"creating agent pod...","parent":"mirrord preparing to launch"}
{"type":"FinishedTask","name":"creating agent pod...","success":true,"message":"agent pod created"}
{"type":"NewTask","name":"waiting for pod to be ready...","parent":"mirrord preparing to launch"}
{"type":"FinishedTask","name":"waiting for pod to be ready...","success":true,"message":"pod is ready"}
{"type":"FinishedTask","name":"mirrord preparing to launch","success":true,"message":"{\"environment\":{"},\"patched_path\":null}"}
/usr/local/bin/mirrord ext -f   0,12s user 0,09s system 0% cpu 1:06,83 total
```
(I removed the hundreds of environment variables)

afterwards I tried to run it with the same config via IDE, waited at least 2min and it was still frozen

**Comment by aviramha** [comment]
Can you also try `mirrord ls -f /xyz/mirrord.json` please?

**Comment by patdlanger** [comment]
> Can you also try `mirrord ls -f /xyz/mirrord.json` please?

it lists all deployments/pods in my configured namespace just fine. Are you interested in anything more specific?

**Comment by Razz4780** [comment]
@patdlanger unfortunately I am unable to reproduce your issue. If you'd like to screen share, there's a "Book time with us" button [here](https://mirrord.dev/#get-support). It might help us in investigation. Thanks!

**Comment by aviramha** [comment]
Another request - can you specify explicitly `kubeconfig` in your mirrord.json? There might be a case your IDE has different env then your terminal.

**Comment by Razz4780** [comment]
Update: we managed to find the bug. Your issue is most probably coming from long delay in communication with your cluster. The fix is on the way :)
